"""Externally supplied proof material for generated theorems (spec §13).

An *external proof* is a tactic script or a witness lemma name that a
caller (today: mumei-agent's AI proof path, ``lean_fallback_strategy =
"ai_generated_proof"``) hands to the bridge for one atom. It replaces only
the generic tactic body that ``ingest_cert.render_theorem`` would emit;
the theorem statement is always regenerated by the translator and is never
taken from the supplier.

Promotion is unchanged: the rendered theorem must survive the real
``lake build`` and every ``scripts/export_cert.py`` contract gate. The
only thing an external proof adds is provenance (``ai_proof_used`` /
``ai_proof_attempts`` on the atom's ``lean_metadata``).

Input file format (``--external-proofs PATH``)::

    {
      "proofs": [
        {
          "atom": "stack_push",
          "module_key": "std/stack",            # optional
          "tactic_script": "intro h\\n  omega",  # or "witness_lemma"
          "source": "ai_generated_proof",        # default
          "attempts": 2                          # optional
        }
      ]
    }
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

AI_GENERATED_PROOF = "ai_generated_proof"
_ALLOWED_SOURCES = frozenset({AI_GENERATED_PROOF, "handwritten_witness"})

# Mirrors mumei-agent ``agent/lean_ai_proof.py::_FORBIDDEN_TOKENS`` so a script
# the agent would refuse is refused here too even when it arrives by file.
FORBIDDEN_TACTIC_TOKENS: Tuple[Tuple[str, "re.Pattern[str]"], ...] = (
    ("sorry", re.compile(r"\bsorry\b")),
    ("admit", re.compile(r"\badmit\b")),
    ("axiom", re.compile(r"\baxiom\b")),
    ("unsafe", re.compile(r"\bunsafe\b")),
    ("implemented_by", re.compile(r"implemented_by")),
    ("extern", re.compile(r"@\[\s*extern")),
    ("native_decide", re.compile(r"\bnative_decide\b")),
    ("run_cmd", re.compile(r"\brun_cmd\b")),
    ("run_tac", re.compile(r"\brun_tac\b")),
    ("eval", re.compile(r"#eval\b|#exit\b|#print\b")),
    ("set_option", re.compile(r"\bset_option\b")),
    ("initialize", re.compile(r"\binitialize\b")),
    (
        "elab",
        re.compile(r"\b(?:macro|macro_rules|elab|elab_rules|syntax|notation)\b"),
    ),
    ("io", re.compile(r"\bIO\.")),
    (
        "declaration",
        re.compile(
            r"(^|\n)\s*(?:theorem|lemma|def|abbrev|instance|axiom|opaque|"
            r"namespace|end|section|import|open|variable|attribute|local|"
            r"scoped|private|protected|noncomputable|partial|structure|"
            r"inductive|class|example)\b"
        ),
    ),
)
_WITNESS_LEMMA_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_'.]*$")


@dataclass(frozen=True)
class ExternalProof:
    atom: str
    tactic_script: Optional[str] = None
    witness_lemma: Optional[str] = None
    module_key: Optional[str] = None
    source: str = AI_GENERATED_PROOF
    attempts: Optional[int] = None

    @property
    def script_sha256(self) -> str:
        return hashlib.sha256(self.proof_text.encode("utf-8")).hexdigest()

    @property
    def proof_text(self) -> str:
        if self.tactic_script is not None:
            return self.tactic_script.strip("\n")
        return f"exact {self.witness_lemma}"

    def render_body(self) -> str:
        """Indented tactic lines that follow ``:= by``."""
        lines = self.proof_text.splitlines() or [""]
        return "\n".join(f"  {line}" if line.strip() else "" for line in lines)

    def provenance(self) -> Dict[str, Any]:
        payload: Dict[str, Any] = {
            "source": self.source,
            "script_sha256": self.script_sha256,
        }
        if self.witness_lemma is not None:
            payload["witness_lemma"] = self.witness_lemma
        if self.attempts is not None:
            payload["attempts"] = self.attempts
        return payload


def reject_unsound_tactic_script(script: str) -> Optional[str]:
    """Return a rejection reason when ``script`` must not reach ``lake``."""
    if not script.strip():
        return "empty_source"
    for label, pattern in FORBIDDEN_TACTIC_TOKENS:
        if pattern.search(script):
            return f"forbidden_token:{label}"
    return None


def reject_external_proof(proof: ExternalProof) -> Optional[str]:
    if proof.source not in _ALLOWED_SOURCES:
        return f"unknown_source:{proof.source}"
    if (proof.tactic_script is None) == (proof.witness_lemma is None):
        return "exactly_one_of_tactic_script_or_witness_lemma_required"
    if proof.witness_lemma is not None:
        if not _WITNESS_LEMMA_RE.match(proof.witness_lemma):
            return "invalid_witness_lemma_name"
        return None
    assert proof.tactic_script is not None
    return reject_unsound_tactic_script(proof.tactic_script)


def parse_external_proofs(payload: Any) -> List[ExternalProof]:
    if isinstance(payload, dict):
        entries = payload.get("proofs", [])
    else:
        entries = payload
    if not isinstance(entries, list):
        raise ValueError("external proofs payload must be a list or {'proofs': [...]}")
    proofs: List[ExternalProof] = []
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict) or not isinstance(entry.get("atom"), str):
            raise ValueError(f"external proof #{index} must be an object with 'atom'")
        attempts = entry.get("attempts")
        proofs.append(
            ExternalProof(
                atom=entry["atom"],
                tactic_script=(
                    str(entry["tactic_script"])
                    if entry.get("tactic_script") is not None
                    else None
                ),
                witness_lemma=(
                    str(entry["witness_lemma"])
                    if entry.get("witness_lemma") is not None
                    else None
                ),
                module_key=entry.get("module_key"),
                source=str(entry.get("source", AI_GENERATED_PROOF)),
                attempts=int(attempts) if attempts is not None else None,
            )
        )
    return proofs


def load_external_proofs(path: Path) -> List[ExternalProof]:
    return parse_external_proofs(json.loads(path.read_text()))


def apply_external_proofs(atoms: Iterable[Any], proofs: Iterable[ExternalProof]) -> Dict[str, str]:
    """Attach accepted proofs to matching ``IngestedAtom`` objects.

    Rejected proofs are recorded on the atom as ``external_proof_rejection``
    and returned as ``{atom_name: reason}``; the atom then keeps whatever
    status it had without the proof, so a rejected script can never promote.
    """
    rejections: Dict[str, str] = {}
    by_atom: Dict[str, List[ExternalProof]] = {}
    for proof in proofs:
        by_atom.setdefault(proof.atom, []).append(proof)
    for atom in atoms:
        candidates = [
            proof
            for proof in by_atom.get(atom.name, [])
            if proof.module_key is None or proof.module_key == atom.module_key
        ]
        if not candidates:
            continue
        proof = candidates[0]
        reason = reject_external_proof(proof)
        if reason is not None:
            atom.external_proof_rejection = reason
            rejections[atom.name] = reason
            continue
        atom.external_proof = proof
    return rejections
